process.env.UV_THREADPOOL_SIZE=1
const cluster = require('cluster')
if(cluster.isMaster){
    console.log('in master')
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
    // cluster.fork()
} else{
    console.log('in slave')
    require('./server')
}